using System.Windows;

// Assembly attributes are generated by the SDK. Keep only WPF theme info here.

[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,
    ResourceDictionaryLocation.SourceAssembly
)]
